# Inteligencia Artificial

## Capítulo 2

### Matemática Básica para Ciencias de Datos

- **Unidad 1.** Introducción
- **Unidad 2.** Matemática Básica para Ciencias de Datos
- **Unidad 3.** Entendiendo las Ciencias de Datos: Vector
- **Unidad 4.** Entendiendo las Ciencias de Datos: Matriz
- **Unidad 5.** Entendiendo las Ciencias de Datos: Derivativas

# Quiz



Alumno: Angel Villegas \
C.I: 29.698.892 \
Correo: angelgasv29@gmail.com

___

## Q 02-01

### Cree ejemplos de vector cero, vector unitario, matriz cuadrada, matriz diagonal, matriz identidad y matriz simétrica uno por uno, y represente vectores y matrices con NumPy.

In [ ]:
# Vector cero

import numpy as np

vector_cero = np.zeros(5)

print(vector_cero)

[0. 0. 0. 0. 0.]


In [ ]:
# Vector unitario

vector = np.array([-3,5])

magnitud = np.linalg.norm(vector) # formula: sqrt (-3)^2 + (5)^2 (Pitagoras) aproximadamente igual a 5.83

vector_unitario = vector / magnitud # formula: -3 / 5.83, 5 / 5.83

print("Vector Unitario: ", vector_unitario)

Vector Unitario:  [-0.51449576  0.85749293]


In [ ]:
# Matriz cuadrada

matriz_cuadrada = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matriz_cuadrada)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Matriz diagonal

matriz_diagonal = np.array([[1,0,0], [0,2,0], [0,0,3]])

print(matriz_diagonal)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
# Matriz identidad

matriz_identidad = np.array([[1,0,0], [0,1,0], [0,0,1]])

print(matriz_identidad)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# Matriz simetrica

matriz_simetrica = np.array([[1, 2, 3], [2, 4, 5],  [3, 5, 6]])

print(matriz_simetrica)


[[1 2 3]
 [2 4 5]
 [3 5 6]]


___

## Q 02-02

### Las acciones de tres empresas A, B y C son 1 millón de wones, 800.000 wones y 500.000 wones, respectivamente. Queremos encontrar la cantidad necesaria para comprar 3, 4 y 5 acciones de estas acciones, respectivamente.

1) Exprese el precio y la cantidad de las acciones como vector p y vector n, respectivamente y codificados con NumPy.

In [ ]:
import numpy as np

# Definir el vector de precios (en wones)
p = np.array([1000000, 800000, 500000])  # precios para A, B y C

# Definir el vector de cantidades
n = np.array([3, 4, 5])  # cantidades de acciones para A, B y C

print("Vector de Precios (p):", p)
print("Vector de Cantidades (n):", n)



Vector de Precios (p): [1000000  800000  500000]
Vector de Cantidades (n): [3 4 5]


2) La cantidad necesaria para comprar acciones se expresa mediante multiplicación y el valor se calcula mediante la operación Numpy.

In [ ]:
cantidad_necesaria = np.dot(p, n)
print("Cantidad necesaria para comprar las acciones:", cantidad_necesaria)

Cantidad necesaria para comprar las acciones: 8700000


___

## Q 02-03

### Cuando se ejecuta el siguiente código, todos los datos de la imagen numérica MNIST se convierten en vectores para crear una única matriz NumPy X. Utilice esta matriz para resolver el siguiente problema.
```
from sklearn.datasets import load_digits
X=load_digits().data
```

1) Encuentre la similitud entre la primera imagen y la décima imagen usando el producto escalar.

In [ ]:
from sklearn.datasets import load_digits
X=load_digits().data

vector_1 = X[0]

vector_10 = X[9]

producto_escalar = np.dot(vector_1, vector_10)

print("El producto escalar entre la primera imagen y la décima imagen es:", producto_escalar)


El producto escalar entre la primera imagen y la décima imagen es: 2807.0


2) Encuentre la similitud para una combinación de todas las imágenes usando el producto escalar, ¿cómo sería eficiente implementarlo (pista: usando matrices y multiplicación de matrices)?


In [ ]:
similitud_matriz = np.dot(X, X.T)

print("Matriz de similitud:\n", similitud_matriz)

Matriz de similitud:
 [[3070. 1866. 2264. ... 2812. 3006. 2898.]
 [1866. 4209. 3432. ... 3906. 3083. 3307.]
 [2264. 3432. 4388. ... 4005. 3063. 3697.]
 ...
 [2812. 3906. 4005. ... 5092. 3729. 4598.]
 [3006. 3083. 3063. ... 3729. 4316. 3850.]
 [2898. 3307. 3697. ... 4598. 3850. 4938.]]


___

## Q 02-04

### Calculate the following inverse matrix.


![matrix.png](attachment:matrix.png)

In [ ]:
import numpy as np

# Definir la matriz A
A = np.array([
    [-1, 4, 0],
    [-1, 3, 1],
    [0, 3, -2]
])

A_inv = np.linalg.inv(A)

print("La matriz inversa es:")
print(A_inv)


La matriz inversa es:
[[-9.  8.  4.]
 [-2.  2.  1.]
 [-3.  3.  1.]]


___

## Q 02-05

### El problema del precio de la vivienda en Boston es un problema de predicción del precio de la vivienda en cada ciudad de Boston (EE.UU.) utilizando características como el índice de delincuencia y la contaminación atmosférica de la zona. Puede importarse del paquete scikit-learn. Encuentre el vector de pesos x cuando el problema del precio de la vivienda en Boston se resuelva con el modelo de predicción lineal Ax=b. Los datos matriciales y vectoriales pueden obtenerse como sigue. Aquí, para simplificar el problema, limitamos los datos de entrada a la tasa de criminalidad (CRIM), la calidad del aire (NOX), el número de habitaciones (RM) y la edad (AGE), y sólo se utilizaron cuatro datos.

Ejecute el código siguiente para comprobar si la magnitud o el signo del vector de pesos obtenido al ejecutar el programa se ajusta a la noción común. Para ello, interprete la salida impresa para todos los factores: CRIM, NOX, RM y EDAD.

(※ Escriba la salida interpretada como "el precio de la vivienda está en proporción inversa a la tasa de criminalidad (CRIM)").
```
from sklearn.datasets import load_boston
boston=load_boston()
X=boston.data
y=boston.target
A = np.array([[0.00632,0.02731,0.02729,0.03237],[0.538,0.469,0.469,0.458],[6.575,6.421,7.185,6.998],[65.2,78.9,61.1,45.8]])

b = np.array([24., 21.6, 34.7, 33.4])
```

In [ ]:
import numpy as np
from numpy.linalg import inv

A = np.array([[0.00632, 0.02731, 0.02729, 0.03237],
              [0.538, 0.469, 0.469, 0.458],
              [6.575, 6.421, 7.185, 6.998],
              [65.2, 78.9, 61.1, 45.8]])

b = np.array([24., 21.6, 34.7, 33.4])

# Calcular el vector de pesos x utilizando la fórmula de la regresión lineal: (A^T A)^(-1) A^T b
x = np.dot(inv(np.dot(A.T, A)), np.dot(A.T, b))

print("Vector de pesos (x):", x)


Vector de pesos (x): [ -443.5894985   1306.42963929 -2737.70620998  2033.88616139]


___

## Fin